# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 16 as the base image for building
FROM node:16 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install the project dependencies
RUN npm install --ignore-scripts

# Copy the rest of the project files
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a lighter Node.js image for the release
FROM node:16-slim AS release

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# The credentials file needs to be mounted in the container
VOLUME [ "/app/gcp-oauth.keys.json" ]

# Expose port 3000
EXPOSE 3000

# Command to run the MCP server
CMD ["node", "build/index.js"]
